### ISSUE TITLE
More Documentation

### ISSUE THREAD

**Issue by akohout** [glittershark/reactable#163]
It's a really cool library, and it was pretty easy to integrate and do the work for me. However, it was harder to get the necessary information.

One PR I send was about the value property on Td components. It's a cool feature, but it wasn't documented (and still isn't for filtering). Another simpler feature is setting the placeholder for the FilterInput. And I bet there are more cool features that keep undiscovered.

I just found these things by searching the repository for certain keywords and then read the code, issues or Pull Requests. I know that documentation is a hard job, but features that are not documented will not be used. 

In my opinion, everyone who sends a PR with a new feature could add a simple example and explanation for the documentation, so that everyone can make use of it.

Then you should think about where to add the complete documentation:

* Do you want to keep everything in the README?
* Do you want to keep the README short and descriptive, then put everything in the Wiki.

**Comment by glittershark** [comment]
I feel like there's a point where we'll outgrow putting all the documentation in the README - but we haven't reached that point yet. I say let's keep all the documentation in the README for now and cross that bridge when we come to it.

I would, however, be totally open to adding more "cookbook"-style examples (here's how to implement this particular use case, etc.) to a wiki

I'm going to close this issue since it's pretty open-ended, but feel free to submit PRs enhancing the documentation in the README.
